---
name: "Docker Build & Push"
description: |
  This action runs docker build with buildx in the context
  and pushed the image to registry

inputs:
  push:
    description: "Push to dockerhub or any other registry"
    default: "true"
    required: false

  tags:
    description: "List of tags for the image"
    default: "latest"
    required: true

  context:
    description: "Docker build context"
    default: "."
    required: false

  dockerfile:
    description: "Path to the Dockerfile"
    required: false

  cache:
    description: "Docker build cache"
    default: "true"
    required: false

  platforms:
    description: "List of image archs for the build"
    default: linux/amd64 # eg: linux/amd64,linux/arm64,linux/arm/v7
    required: false

  repository_name:
    description: "Repo name on dockerhub"
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:master
        install: true

    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-${{ inputs.repository_name }}
        key: ${{ runner.os }}-buildx-${{ inputs.repository_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.repository_name }}-
          ${{ runner.os }}-buildx-

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: tykio/${{ inputs.repository_name }}
        tags: |
          type=sha
          type=semver,pattern={{raw}},value=${{ inputs.tags }}

    - uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.repository_name }}
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-${{ inputs.repository_name }}-new
