---
name: Terraform Formatter
description: Runs terraform validate and format
inputs:
  terraform_version:
    description: 'Terraform version'
    required: true
    default: 0.12.31
runs:
  using: "composite"
  steps:
    - name: Run test
      shell: bash
      run: |
        mkdir -p $TF_PLUGIN_CACHE_DIR
        cat <<EOF > provider.ci.tf
          provider "aws" {
            region = "eu-central-1"
          }
          provider "kubernetes" {}
          provider "helm" {}
        EOF
        terraform fmt -write=true provider.ci.tf

    - name: Terraform init
      shell: bash
      run: terraform init

    - name: Terraform validate
      shell: bash
      run: terraform validate

    - name: Terraform fmt
      shell: bash
      run: terraform fmt -check -recursive -diff .
