---
name: TFlint
description: Runs TFLint
inputs:
  github_token:
    description: 'Github Token'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('./config/.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.47.0

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.18.1

    - name: Show version
      run: tflint --version
      shell: bash

    - name: Init TFLint
      run: tflint --init
      shell: bash

    - name: Run TFLint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        tflint -c $(pwd)/config/.tflint.hcl  --force -f=checkstyle . > "results.xml"
        cat results.xml | reviewdog -f=checkstyle -name="TFLint" -reporter=github-pr-check -level=warning
