---
name: TFlint
description: Runs TFLint
inputs:
  github_token:
    description: 'Github Token'
    required: true


runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('./config/.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.51.1

    - name: tflint
      uses: reviewdog/action-tflint@v1
      with:
        github_token: ${{ inputs.github_token }}
        fail_on_error: "true" # Optional. Fail action if errors are found
#        level: warning
