name: "My Composite Action"
description: "An example composite action"
inputs:
  some-input:
    description: "Example input"
    required: true
    default: "default-value"

runs:
  using: "composite"
  steps:
    - name: Print input value
      shell: bash
      run: |
        echo "Input value: ${{ inputs.some-input }}"