---
name: "Check docker tag exists"
description: |
  Checks whether a particular image tag exists in any of the
  private/public repo on DockerHub.

inputs:
  registry_name:
    description: "Registry name"
    required: true
  tag:
    description: "Tag of the image"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable experimental features for the Docker daemon and CLI
      shell: bash
      run: |
        echo $'{\n "experimental": true\n}' | sudo tee /etc/docker/daemon.json
        mkdir -p ~/.docker
        echo $'{\n "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
        sudo service docker restart
        docker version -f '{{.Client.Experimental}}'
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
        ecr: false

    - name: Check tag availability
      shell: bash
      run: |
        STATUS=$(curl -s -f -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/${{ inputs.registry_name }}/tags/${{ inputs.tag }}/)
        if [ "${STATUS}" == "200" ]; then
          echo "Tag ${{ inputs.tag }} exists"
        else
          echo "Tag ${{ inputs.tag }} doesn't exist" >&2
          exit 1;
        fi
