---
name: "Check docker tag exists"
description: |
  This action checks whether a particular image tag exists in any of the
  private/public repos on DockerHub.
inputs:
  registry_name:
    description: "Registry name"
    required: true
  tag:
    description: "Tag of the image"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        tmp=$(mktemp)
        sudo jq '.+{experimental:true}' /etc/docker/daemon.json > "$tmp"
        sudo mv "$tmp" /etc/docker/daemon.json
        sudo systemctl restart docker.service

    - shell: bash
      run: |
        STATUS=$(curl -s -f -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/${{ inputs.registry_name }}/tags/${{ inputs.tag }}/)
        if [ "${STATUS}" == "200" ]; then
          echo "Tag ${{ inputs.tag }} exists"
        else
          echo "Tag ${{ inputs.tag }} doesn't exist" >&2
          exit 1;
        fi
