---
name: Lint PR
on:
  workflow_call:
    inputs:
      scopes:
        required: false
        type: string
        default: ""
      types:
        required: false
        type: string
        default: ""

jobs:
  lint:
    name: Validate PR Title
    if: github.event.action == 'opened' || github.event.changes.title.from
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
            feat
            fix
            chore
            refactor
            CI
            test
            docs
            style
            perf
            test
            build
            revert
            TD
            TT
            ${{ inputs.types }}

        scopes: |
            TD-\d+
            TT-\d+
            ${{ inputs.scopes }}
