---
name: Test
on:
  workflow_call:
    inputs:
      terraform_versions:
        description: 'Comma-separated Terraform versions'
        required: false
        type: string
        default: "0.12.31"
      testmode:
        description: 'Flag to indicate if execute action as local should be run'
        required: false
        type: boolean
        default: false
      before_script:
        description: 'Extra commands to run before running tests'
        required: false
        type: string
        default: "echo No before script"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Set up Terraform versions matrix
        id: setup-matrix
        run: |
          versions="${{ inputs.terraform_versions }}"
          matrix=$(echo $versions | jq -R 'split(",") | map({terraform_version: .})'| jq -c .)
          echo "matrix={\"include\": ${matrix}}" >> $GITHUB_OUTPUT


  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout invoker repository
        uses: actions/checkout@v4    

      - name: Test action if testmode
        if: ${{ inputs.testmode }}
        uses: ./.github/actions/tflint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tflint
        id: tflint
        if: ${{ !inputs.testmode }}
        uses: TykTechnologies/actions/.github/actions/tflint@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  formatter:
    name: Formatter
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    env:
      TF_PLUGIN_CACHE_DIR: /tmp/.terraform/plugins
      TERRAFORM_VERSION: 0.12.31
    steps:

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Before script
        run: |
          ${{ inputs.before_script }}
        shell: bash

      - name: Checkout action repository if testmode
        if: ${{ inputs.testmode }}      
        uses: actions/checkout@v4

      - name: Test action if testmode
        if: ${{ inputs.testmode }}
        uses: ./.github/actions/terraform-format
        with:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}          

      - name: Terraform Format, Lint and Validate
        if: ${{ !inputs.testmode }}
        id: terraform-format
        uses: TykTechnologies/actions/.github/actions/terraform-format@main
        with:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
